openapi: 3.0.0
info:
  title: Order API
  version: 1.0.0
paths:
  /order:
    post:
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  format: uuid
                amount:
                  type: integer
                  format: int64
                description:
                  type: string
      responses:
        '201':
          description: Order created successfully
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

  /orders:
    get:
      summary: Get list of orders for user
      parameters:
        - in: query
          name: user_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

  /order/{order_id}/status:
    get:
      summary: Get order status
      parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Order status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderStatusResponse'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

components:
  schemas:
    ApiErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
    OrderResponse:
      type: object
      properties:
        order_id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        description:
          type: string
        status:
          type: string
        amount:
          type: integer
          format: int64
    OrderStatusResponse:
      type: object
      properties:
        order_id:
          type: string
          format: uuid
        status:
          type: string
